### PR TITLE
Major Updates

### PR DESCRIPTION
**Pull request by dennisreimann**
hey @jasonm, I recently made some minor updates to the gem and later saw, that other people added a lot of useful stuff like specs and pusher integration. most of that work was done by @patricksrobertson , I just curated most of that. It would be great if this could be merged to the main repo as it's got a proper test suite and some useful additions.

### CODE REVIEW

**Comment by dennisreimann** [comment]
@jasonm can you provide feedback for that or mention things that'd need to be changed?

**Comment by patricksrobertson** [comment]
I couldn't even get Jason to pull these things in while we were on the same development team :P.  I keep most of these changes alive in my fork of:

https://github.com/iorahealth/backbone_sync-rails

**Comment by dennisreimann** [comment]
@patricksrobertson so, basically, the gem isn't maintained anymore?

**Comment by jasonm** [comment]
Yikes whoa wow - somehow I missed the notification on this originally.  Sorry about that.  It's true that I haven't actively maintained this.  I'm happy to merge and review this, but since I'm not actively using the gem, it's less likely I'll be the best one to maintain it.

Apparently there are 5 pull reqs, not sure how I missed these.  Maybe they were lost in a flood of iorahealth pull req notifications ;)

@patricksrobertson how do you feel about making iorahealth the canonical repo?  I'm happy to give ownership over the rubygems.org gem.

**Comment by patricksrobertson** [comment]
@jasonm I think we can aim to make the Iora fork the canonical source.  I'm all for more people using a library so I stop developing things that are easy for just my use case.

**Pull request closed without merging**
